//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Case_Study
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public int id { get; set; }
        public string Rname { get; set; }
        public string City { get; set; }
        public string Branch { get; set; }
        public string Fooditem1 { get; set; }
        public Nullable<int> Price { get; set; }
        public byte[] Img { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
