//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Case_Study
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id { get; set; }
        public string UserId { get; set; }
        public string Restaurant { get; set; }
        public string Branch { get; set; }
        public string FoodItem { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> DaTi { get; set; }
    }
}
